/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package funcdraw;

import javax.swing.JOptionPane;

/**
 *
 * @author yazeed44
 */
public class FuncDrawMain extends javax.swing.JFrame {

    /**
     * Creates new form FuncDrawMain
     */
    public FuncDrawMain() {
        
        initComponents();
        fxText.setText("x");
        graphPanel.setEquation(fxText.getText());
        this.setTitle("النسخة التجريبية  : تمثيل المعادلات بيانيا");
        this.setResizable(false);
        JOptionPane.showMessageDialog(this, "امثلة على طريقة كتابة الدوال : " + "\n" + "2 * x + cos(x)" + "\n" +"x ^ 2 - 5" +"\n"+ "ملاحظة : "+ "\n"
                +"يفضل استخدام الاقواس", "", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

       
        jLabel1 = new javax.swing.JLabel();
        fxText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        xMax = new javax.swing.JTextField();
        graphDrawBtn = new javax.swing.JButton();
 fxText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fxText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fxText.setText("sin(x)");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

 xMax.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xMax.setText("6");
        
 graphPanel = new PlotFunctionPanel(this,402,Integer.parseInt(xMax.getText()),fxText.getText());
        graphPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("f(x)=");

       

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("اعلى عدد لـ x = ");

       

        graphDrawBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        graphDrawBtn.setText("ارسم المعادلة");
        graphDrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphDrawBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(xMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fxText, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(graphDrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(xMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graphDrawBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graphDrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphDrawBtnActionPerformed
        // TODO add your handling code here:
        
        String fxStr = fxText.getText();
        
        int xMaxInt = Integer.parseInt(xMax.getText());
        
        if(fxStr == null || fxStr.length() == 0){//check to make sure
            JOptionPane.showMessageDialog(this, "لايوجد معادلة !!", "خطأ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        graphPanel.setMaxValue(xMaxInt);
        graphPanel.setEquation(fxStr);
        
        String message = "هذه المعلومات قد لاتكون دقيقة 100% لان هذه النسخة تجريبية"+"\n" + "معلومات عن الدالة : " +fxStr+ "\n"+ graphPanel.getDomain(fxStr) + "\n" + graphPanel.getRange(fxStr) + "\n"
                + graphPanel.getSmallestFxValue(fxStr) + "\n" + graphPanel.getYPart(fxStr) + "\n" + graphPanel.getZeros(fxStr)
                +"\n" + graphPanel.getAverageResult(fxStr) + "\n" + graphPanel.getFuncType(fxStr) + "\n" + graphPanel.getInversedFunction(fxStr) ;
     
        JOptionPane.showMessageDialog(this, message,"معلومات عن الدالة", JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_graphDrawBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncDrawMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncDrawMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncDrawMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncDrawMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FuncDrawMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fxText;
    private javax.swing.JButton graphDrawBtn;
    private PlotFunctionPanel graphPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField xMax;
    // End of variables declaration//GEN-END:variables
}
